### ISSUE TITLE
Example project fails to serve

### ISSUE THREAD

**Issue by spritefullake** [bartblast/hologram#78]
Firstly, really great concept to make a client side state tracking with elixir. 

I'm trying to get the example program to work, I have the Hologram library as a dependency. However, there is no Hologram.Page module that is found. 

So I also downloaded the overhaul/test/e2e folder and running mix phx.server also fails because of errors like ````** (UndefinedFunctionError) function Hologram.Compiler.Transformer.transform/2 is undefined or private````

If there is an easy migration pathway from a normal phoenix project generated using ````mix phx.new```` to a hologram project that would be great. But as of now, I am not able to get the example program to work.

**Comment by bartblast** [comment]
Hey @spritefullake, you won't be able to run the master version of the code since I've been doing a big overhaul for the last couple of months and it's not finished/working. BTW the readme/roadmap is not up to date, actually, most of the syntax is already done.

To get the source code for the 0.1.0 release which works with the readme (together with e2e app), use this source code tree:
https://github.com/bartblast/hologram/tree/27df62fa008a60a612d23f4c0dc4989d1e92b418
or checkout to this commit: https://github.com/bartblast/hologram/commit/27df62fa008a60a612d23f4c0dc4989d1e92b418
